# Generated by Django 5.1.15 on 2026-05-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('flows', '0001_initial'),
        ('transfers', '0002_cleanup_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferjob',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='flows.flow'),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='connections.connection'),
        ),
    ]
