# Generated by Django 5.1.15 on 2026-07-01 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transferjob_flow_alter_transferjob_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferjob',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('running', 'RUNNING'), ('done', 'DONE'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED')], default='pending', max_length=10),
        ),
    ]
