# Generated by Django 5.1.15 on 2026-07-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transfers_retention_periodic_task'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE transfers_transferjob "
                "SET celery_task_id = '' WHERE celery_task_id IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE transfers_transferjob "
                "SET error_message = '' WHERE error_message IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
