# Generated by Django 5.1.15 on 2026-07-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_alter_transferjob_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
