# Generated by Django 5.1.15 on 2026-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_alter_transferjob_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferjob',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
