sonar.projectKey=tmasktt
sonar.projectName=TMaskTT
sonar.sources=./
sonar.exclusions=**/migrations/**,**/templates/**
sonar.python.version=3.12
sonar.host.url=http://10.254.0.1:9000
sonar.token=sqp_9dfbfdb6fb27c60ba37c1dbde69212b68a85ca93