sonar.projectKey=tmasktt
sonar.projectName=TMaskTT
sonar.sources=./
sonar.exclusions=**/migrations/**,**/templates/**,**/tests/**,**/conftest.py
sonar.python.version=3.12
sonar.host.url=http://10.254.0.1:9000
sonar.token=REPLACE_WITH_YOUR_SONARQUBE_TOKEN