# Generated by Django 5.1.15 on 2026-07-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_connection_kind_and_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='db_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
