# Generated by Django 5.1.15 on 2026-07-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_alter_connection_db_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE connections_connection SET known_host_key = '' WHERE known_host_key IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='connection',
            name='known_host_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
