# Generated by Django 5.1.15 on 2026-07-20 19:36

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_alter_connection_known_host_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='ssh_key_passphrase',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
    ]
