# Generated by Django 5.1.15 on 2026-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_connection_ssh_key_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='kind',
            field=models.CharField(choices=[('ssh', 'SSH'), ('postgres', 'Postgres'), ('mysql', 'MySQL'), ('mssql', 'MSSQL')], default='ssh', max_length=10),
        ),
    ]
