# Generated by Django 5.1.15 on 2026-05-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('flows', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransfer',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='flows.flow'),
        ),
        migrations.AlterField(
            model_name='scheduledtransfer',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='scheduledtransfer',
            name='destination_path',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='scheduledtransfer',
            name='source_path',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
