# Generated by Django 5.1.15 on 2026-07-01 15:51

from django.db import migrations, models


def migrate_user_role_to_operator(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='user').update(role='operator')


def reverse_operator_role_to_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='operator').update(role='user')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegram_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_user_role_to_operator, reverse_operator_role_to_user),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('readonly', 'Read-only')], default='operator', max_length=10),
        ),
    ]
