# Generated by Django 5.1.15 on 2026-07-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webhook_circuit_open_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='webhook_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
