# Generated by Django 5.1.15 on 2026-05-21 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_path', models.CharField(max_length=2000)),
                ('dest_path', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dest_conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_flows', to='connections.connection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to=settings.AUTH_USER_MODEL)),
                ('source_conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_flows', to='connections.connection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
