# Generated by Django 5.1.15 on 2026-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='verify_checksum',
            field=models.BooleanField(default=False),
        ),
    ]
