# Generated by Django 5.1.15 on 2026-07-29 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0009_connection_kind_mysql_mssql'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('faker_provider', models.CharField(choices=[('first_name', 'Imię'), ('last_name', 'Nazwisko'), ('name', 'Imię i nazwisko'), ('email', 'E-mail'), ('phone_number', 'Telefon'), ('street_address', 'Adres (ulica)'), ('city', 'Miasto'), ('postcode', 'Kod pocztowy'), ('country', 'Kraj'), ('company', 'Firma'), ('job_title', 'Stanowisko')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masking_rules', to='connections.connection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masking_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reguła maskowania',
                'verbose_name_plural': 'Reguły maskowania',
                'ordering': ['connection', 'table_name', 'column_name'],
                'unique_together': {('connection', 'table_name', 'column_name')},
            },
        ),
    ]
