# Generated by Django 5.1.15 on 2026-07-01 18:39

from django.core.management.color import no_style
from django.db import migrations, models


def create_default_organization(apps, schema_editor):
    Organization = apps.get_model('organization', 'Organization')
    Organization.objects.get_or_create(pk=1, defaults={'name': 'Organizacja'})
    # Explicitly inserting pk=1 bypasses the DB's auto-increment sequence,
    # so the next auto-assigned id would also be 1 and collide. Resync it.
    sequence_sql = schema_editor.connection.ops.sequence_reset_sql(no_style(), [Organization])
    for sql in sequence_sql:
        schema_editor.execute(sql)


def remove_default_organization(apps, schema_editor):
    Organization = apps.get_model('organization', 'Organization')
    Organization.objects.filter(pk=1, name='Organizacja').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(create_default_organization, remove_default_organization),
    ]
