# Generated by Django 5.1.15 on 2026-07-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_transfers', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE db_transfers_pgtransferjob "
                "SET celery_task_id = '' WHERE celery_task_id IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE db_transfers_pgtransferjob "
                "SET error_message = '' WHERE error_message IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='pgtransferjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pgtransferjob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
