# Generated by Django 5.1.15 on 2026-07-21 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_connection_kind_mysql_mssql'),
        ('db_transfers', '0002_alter_pgtransferjob_celery_task_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PgTransferJob',
            new_name='DbTransferJob',
        ),
        migrations.RenameModel(
            old_name='PgTransferLog',
            new_name='DbTransferLog',
        ),
        migrations.AddField(
            model_name='dbtransferjob',
            name='engine',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('mysql', 'MySQL'), ('mssql', 'MSSQL')], default='postgres', max_length=10),
            preserve_default=False,
        ),
    ]
