# Generated by Django 5.1.15 on 2026-07-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_connection_kind_mysql_mssql'),
        ('db_transfers', '0003_rename_pg_to_db_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtransferjob',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_db_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dbtransferjob',
            name='dest_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_dest_jobs', to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='dbtransferjob',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dbtransferjob',
            name='source_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_source_jobs', to='connections.connection'),
        ),
    ]
